use_frameworks!

platform :ios, '9.0'

target 'KHWKWebViewControllerKit_Example' do
  pod 'KHWKWebViewControllerKit', :path => '../'

  target 'KHWKWebViewControllerKit_Tests' do
    inherit! :search_paths

    
  end
end
